# Generated by Django 4.2.1 on 2023-06-08 08:03

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=400)),
                ('s_desc', ckeditor.fields.RichTextField()),
                ('s_pic', models.ImageField(null=True, upload_to='media/serviceimage')),
                ('is_active', models.BooleanField(default=True)),
                ('s_rank', models.IntegerField(default=0)),
            ],
        ),
    ]
