# Generated by Django 4.2.1 on 2023-06-13 08:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=400)),
                ('client_desc', ckeditor.fields.RichTextField()),
                ('client_pic', models.ImageField(null=True, upload_to='media/serviceimage')),
                ('is_active', models.BooleanField(default=True)),
                ('client_rank', models.IntegerField(default=0)),
            ],
        ),
    ]
