# Generated by Django 4.2.2 on 2023-06-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='client_pos',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
