# Generated by Django 4.2.2 on 2023-06-17 03:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_testimonials_client_pos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=400)),
                ('staff_pos', models.CharField(max_length=200, null=True)),
                ('staff_desc', ckeditor.fields.RichTextField()),
                ('staff_pic', models.ImageField(null=True, upload_to='media/serviceimage')),
                ('is_active', models.BooleanField(default=True)),
                ('staff_rank', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='testimonials',
            name='client_rank',
        ),
        migrations.RemoveField(
            model_name='testimonials',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='client_pic',
            field=models.ImageField(null=True, upload_to='media/testimonialsimage'),
        ),
    ]
