# Generated by Django 4.2.2 on 2023-06-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_team_facebook_team_gmail_team_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='client_pos',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
