# Generated by Django 4.2.2 on 2023-06-19 05:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_testimonials_client_pos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=400)),
                ('p_type', models.CharField(max_length=200, null=True)),
                ('p_desc', ckeditor.fields.RichTextField()),
                ('p_pic', models.ImageField(null=True, upload_to='media/projectimage')),
                ('is_active', models.BooleanField(default=True)),
                ('p_rank', models.IntegerField(default=0)),
                ('p_point1', models.CharField(max_length=200)),
                ('p_point2', models.CharField(blank=True, max_length=200, null=True)),
                ('p_point3', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
