# Generated by Django 4.2.2 on 2023-06-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='is_active',
        ),
        migrations.AddField(
            model_name='team',
            name='is_md',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='p_point2',
            field=models.CharField(max_length=200),
        ),
    ]
