# Generated by Django 4.2.2 on 2023-06-20 09:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_team_is_active_team_is_md_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=400)),
                ('b_type', models.CharField(max_length=200, null=True)),
                ('b_rank', models.IntegerField(default=0)),
                ('b_pic', models.ImageField(null=True, upload_to='media/blogimage')),
                ('b_desc', ckeditor.fields.RichTextField()),
                ('b_point1', models.CharField(max_length=200)),
                ('b_point2', models.CharField(max_length=200)),
                ('b_point3', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
