# Generated by Django 4.2.2 on 2023-06-20 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_blog_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='b_point1',
            new_name='b_tag1',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='b_point2',
            new_name='b_tag2',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='b_point3',
            new_name='b_tag3',
        ),
    ]
