# Generated by Django 4.2.2 on 2023-06-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='b_tag1',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='b_tag2',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='b_tag3',
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=200, null=True),
        ),
    ]
