# Generated by Django 4.2.2 on 2023-06-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_blog_b_tag1_remove_blog_b_tag2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='short_desc',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.CharField(help_text='Comma-separated tags', max_length=200),
        ),
    ]
