# Generated by Django 4.2.2 on 2023-06-26 10:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_blog_short_desc_alter_blog_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='blog',
            name='short_desc',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.CharField(help_text='Comma-separated tags', max_length=100),
        ),
    ]
