# Generated by Django 4.2.2 on 2023-06-26 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_project_timestamp_alter_blog_short_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
