# Generated by Django 4.2.2 on 2023-06-26 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_project_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.CharField(help_text='Comma-separated tags', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.CharField(help_text='Comma-separated tags', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='p_pic',
            field=models.ImageField(upload_to='media/projectimage'),
        ),
        migrations.AlterField(
            model_name='project',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
