# Generated by Django 4.2.2 on 2023-07-18 01:49

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_project_tags_alter_blog_tags_alter_blog_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=400)),
                ('c_type', models.CharField(max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('c_rank', models.IntegerField(default=0)),
                ('c_pic', models.ImageField(upload_to='media/courseimage')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('c_desc', ckeditor.fields.RichTextField()),
                ('c_point1', models.CharField(max_length=200)),
                ('c_point2', models.CharField(max_length=200)),
                ('c_point3', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
