# Generated by Django 4.2.2 on 2023-07-18 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_course_c_point1_remove_course_c_point2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='c_tags',
            field=models.CharField(help_text='Comma-separated tags', max_length=100, null=True),
        ),
    ]
