# Generated by Django 4.2.2 on 2023-07-18 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_course_c_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='c_content',
        ),
    ]
